version: '3.8'

services:
  db:
    build: .
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432